apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: registry.cn-beijing.aliyuncs.com/oblp/post-service
      context: article-api
  local: {}
deploy:
  kubectl:
    manifests:
      - k8s/development/main.yaml
profiles:
  - name: testing-profile
  - name: staging-profile
  - name: production-profile
  - name: development-profile

