apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
    - image: registry.cn-beijing.aliyuncs.com/oblp/post-service
      jib:
        project: post-service-api
deploy:
  kubectl:
    manifests:
      - development/deployment.yaml
      - development/service.yaml
      - development/ingress.yaml
profiles:
  - name: develop