debug: true

logging:
  level:
    org.springframework.web: DEBUG

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test
    username: root
    password: helloworld

  jpa:
    hibernate:
      ddl-auto: update